### PR TITLE
Prevent crash when a target class is not located with better logging mechanism.

### LINKED ISSUE #27: Annotator fails when a Fix targeting an element in a generated code is suggested.
**Describe the bug**
In the process of measuring effectiveness of fixes, if a fix is targeting an element in the generated code, `Injector` will throw an exception that it could not find the class which does not exist.

**To Reproduce**
Use a `lombok` builder and target a method in the `builder` class.

**Expected behavior**
`Injector` should report these classes silently when the class is not found and should not terminate the process.

**Screenshots**
Not-Applicable.

**Additional context**
No Additional Context.

### PR DESCRIPTION
**Pull request by nimakarimipour**
This PR fixes #27 by adding a new type of exception `TargetClassNotFound`. With this PR annotator will not crash if the class is not found, and will instead log this information for later debugging. 

Also added a test to verify, annotator will not fail and the desired error message is correctly reported in the `err` console.

### CODE REVIEW

File: injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java [hunk 1]
```diff
@@ -210,6 +219,9 @@ private static Node findTopLevelAnonymousClass(Node cursor, int index) {
           }
           return false;
         });
+    if (index >= candidates.size()) {
+      throw new TargetClassNotFound("Top-Level-Anonymous-Class", "$" + index, cursor);
+    }
```
Comment (lazaroclapp) [inline injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java:224]: This might not be quite as easy as this, though... what happens if there are `Foo$1`, `Foo$2`, and `Foo$3`, but it is `Foo$2` that is generated? We might some additional information from NullAway to handle this properly in the case of anonymous classes specifically (Fortunately, Lombok generated _anonymous_ classes is not something I have run into, at least outside of Lombok-generated methods. Still, I wonder if we should fail loudly in that case, rather than silently pick the wrong anonymous inner class)

File: injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java [hunk 2]
```diff
@@ -149,10 +148,14 @@ private static TypeDeclaration<?> findTopLevelClassDeclarationOnCompilationUnit(
...
     Optional<ClassOrInterfaceDeclaration> interfaceDeclaration = tree.getInterfaceByName(name);
-    return interfaceDeclaration.orElseGet(() -> tree.getClassByName(name).orElse(null));
+    if (interfaceDeclaration.isPresent()) {
+      return interfaceDeclaration.get();
+    }
+    throw new TargetClassNotFound("Top-Level", name, tree);
   }
 
-  public static Node findTopLevelDirectInnerClass(Node cursor, String name) {
+  private static Node findTopLevelDirectInnerClass(Node cursor, String name)
```
Comment (lazaroclapp) [inline injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java:157]: Even though these are private methods, I think they would benefit from Javadocs. What is the difference between a "Top level direct inner class" and a "top level inner class", for example?

File: injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java [hunk 3]
```diff
@@ -161,26 +164,31 @@ public static Node findTopLevelDirectInnerClass(Node cursor, String name) {
...
     walk(
         cursor,
         candidates,
         node -> {
           Optional<Node> parent = node.getParentNode();
-          if (!parent.isPresent()) {
+          if (parent.isEmpty()) {
             return false;
           }
           if (parent.get().equals(cursor)) {
```
Comment (lazaroclapp) [inline injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java:184]: Question: What is this line checking for?

File: injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java (hunk 1 above)
Comment (lazaroclapp) [reply injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java:224]: Either way: worth tracking as a future task somewhere. Not high priority, but definitely a potential pitfall/bug.

**Review by lazaroclapp — COMMENTED** [review]
Some comments. Also, a slight meta-comment: it's worth it for the PR to have a title that directly explains what the fix is about rather than an indirect reference to an issue. You can always link the issue in the description, but the commit message is a) more easily visible and b) more permanent in the codebase than any issue on any tracker.

File: injector/src/main/java/edu/ucr/cs/riple/injector/exceptions/TargetClassNotFound.java [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+ */
+
+package edu.ucr.cs.riple.injector.exceptions;
+
+import com.github.javaparser.ast.Node;
+
+public class TargetClassNotFound extends Exception {
+
+  static final String REPORT_MESSAGE =
+      "If you do see the class on the source code, please report this bug at: https://github.com/nimakarimipour/NullAwayAnnotator/issues. Thank you!";
```
[the remark this answers is not in the document]
Comment (nimakarimipour) [reply injector/src/main/java/edu/ucr/cs/riple/injector/exceptions/TargetClassNotFound.java]: 67effbd9328f8c587712d6ceb5b8d010bc9ab0fc

File: injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java (hunk 3 above)
Comment (nimakarimipour) [reply injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java]: Actually this was needed for previous approach, with the new `walk` method I wrote, this is not required anymore. Deleted it. 92b769bb4cd4e901a774a89f74e3d690f9cc40d6

File: injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java (hunk 1 above)
Comment (nimakarimipour) [reply injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java:291]: Sure, that's a good point. Will create an issue once this lands, to track it.

File: injector/src/test/java/edu/ucr/cs/riple/injector/ClassSearchTest.java [hunk 5]
```diff
@@ -468,4 +475,32 @@ public void class_search_benchmark_22() {
                 true))
         .start(true);
   }
+
+  @Test
+  public void proper_report_for_class_not_found_test() {
```
[the remark this answers is not in the document]
Comment (nimakarimipour) [reply injector/src/test/java/edu/ucr/cs/riple/injector/ClassSearchTest.java]: Actually I wanted to divide it into two steps, but that requires hardcoding the expected error message. Which, if we change the message, we need to update the tests as well. However, it makes more sense to divide it to two cases in favor of cohesiveness of each test.

9d5f3188f1500967ef879e7979ee0cc87b751adc

Please let me know if you prefer the older version.

File: injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java (hunk 2 above)
Comment (nimakarimipour) [reply injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java]: Added javadocs for all methods in this class. I am planning to add javadoc through every PR :) c623aacf3634525f48470ead8e8d3506348029d6

Direct inner class requires the class to be connected to parent directly, and the other one does not have this constraint. `top level` name is also removed from them, they are on `findDirectInnerClass` and `findInnerClass`.

**Comment by nimakarimipour** [comment]
@lazaroclapp This is ready for another review.

File: injector/src/test/java/edu/ucr/cs/riple/injector/ClassSearchTest.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (lazaroclapp) [reply injector/src/test/java/edu/ucr/cs/riple/injector/ClassSearchTest.java]: Hardcoding the expected message in tests and having to change the tests when behavior changes is very reasonable. In production code, I'd err on the side of not hardcoding things and avoiding repetition, since that makes the code fragile. But within unit tests, clarity is more important, and I'd argue that failing when existing behavior changes is a feature, not a bug, of a comprehensive test suite :)

File: injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java [hunk 6]
```diff
@@ -50,8 +50,16 @@
 import me.tongfei.progressbar.ProgressBar;
 import me.tongfei.progressbar.ProgressBarStyle;
 
+/** A utility class. */
 public class Helper {
 
+  /**
+   * Extracts the callable simple name from callable signature. (e.g. in input "run(Object i)"
```
Comment (lazaroclapp) [inline injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java:57]: "on input"

File: injector/src/test/java/edu/ucr/cs/riple/injector/ClassSearchTest.java [hunk 7]
```diff
@@ -493,14 +503,32 @@ public void proper_report_for_class_not_found_test() {
                 "javax.annotation.Nullable",
                 true))
         .start();
-    String errOutput = err.toString();
+    assert err.toString().equals(expectedErrorMessage);
```
Comment (lazaroclapp) [inline injector/src/test/java/edu/ucr/cs/riple/injector/ClassSearchTest.java:506]: Don't use java assert directly in tests, prefer JUnit's assertion APIs, such as `assertEquals(...)` or `assertTrue(...)`. That way we don't depend on whether assertions are kept by the compiler or not (subject to compiler configuration)

File: injector/src/test/java/edu/ucr/cs/riple/injector/ClassSearchTest.java [hunk 8]
```diff
@@ -477,7 +477,17 @@ public void class_search_benchmark_22() {
   }
 
   @Test
-  public void proper_report_for_class_not_found_test() {
+  public void proper_report_in_err_std_for_class_not_found_test() {
+    String expectedErrorMessage =
```
Comment (lazaroclapp) [inline injector/src/test/java/edu/ucr/cs/riple/injector/ClassSearchTest.java:481]: Thinking about these long errors, we probably should just be testing a substring. Something like:

```
String expectedErrorMessage = "Could not find class of type: Top-Level with name: NotIncluded"
[...]
assertTrue(err.toString().contains(expectedErrorMessage));
```

File: injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java [hunk 9]
```diff
@@ -131,6 +163,16 @@ private static void walk(Node cursor, List<Node> candidates, Predicate<Node> pre
         });
   }
 
+  /**
+   * Finds Top-Level type declaration within a {@link CompilationUnit} tree by name, this node is
+   * direct child of the compilation unit tree and can be: [{@link ClassOrInterfaceDeclaration},
```
Comment (lazaroclapp) [inline injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java:168]: Missing article? Either "a direct child" or "the direct child"

File: injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java [hunk 10]
```diff
@@ -66,43 +74,57 @@ public static String extractCallableName(String signature) {
...
   }
 
+  /**
+   * Checks if callableDec's signature is equals to signature passed in the argument.
+   *
+   * @param callableDec callable declaration node.
+   * @param signature signature of the callable in string.
+   * @return true, if signature matches the callable and false otherwise.
+   */
   public static boolean matchesCallableSignature(
```
Comment (lazaroclapp) [inline injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java:92]: Definitely not for this PR, but I notice there are a lot of methods here comparing signatures in String format to `CallableDeclaration` by parsing the string multiple times and extracting different portions of it: wouldn't it be more useful to have a single function parsing a string into it's corresponding `CallableDeclaration`? In fact, if the only comparison we need is strict equality, a well crafted `CallableDeclaration.toString()` method could be all we need here, no parsing required.

Comment (nimakarimipour) [reply injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java]: Hi @lazaroclapp, sure that sounds good. However, at the moment I was writing `injector` it wasn't merged into annotator as a sub-module and I was intending to make a robust tool that works with any given signature, not necessarily matching how `error prone` serializes methods signature. It now works with any given input as long as the types and names and correct (simple name or fully qualified name). However, what you mention about parsing it multiple times is a really good point and it worths to address it in this PR. Please find it here where we only parse each signature once. 13ee6712184d74d1edea5e155f3967f5b2c86b57.

File: injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java (hunk 9 above)
Comment (nimakarimipour) [reply injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java:185]: 6079a72c488c2b651b698a6d88a0c7d29aaa784e

File: injector/src/test/java/edu/ucr/cs/riple/injector/ClassSearchTest.java (hunk 7 above)
Comment (nimakarimipour) [reply injector/src/test/java/edu/ucr/cs/riple/injector/ClassSearchTest.java]: e8040841a6b3d56eb5d1a8798052acabcd760a11

File: injector/src/test/java/edu/ucr/cs/riple/injector/ClassSearchTest.java (hunk 8 above)
Comment (nimakarimipour) [reply injector/src/test/java/edu/ucr/cs/riple/injector/ClassSearchTest.java]: e8040841a6b3d56eb5d1a8798052acabcd760a11

File: injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java (hunk 6 above)
Comment (nimakarimipour) [reply injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java]: c5d0438d0fdadee93ad046724bab696703a88919

File: injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java [hunk 11]
```diff
@@ -53,8 +53,62 @@
...
+    private final List<String> parameterTypes;
+
+    /**
+     * Constructor to make a matcher instance.
+     *
+     * @param signature Signature to process.
+     */
+    public SignatureMatcher(String signature) {
+      this.callableName = extractCallableName(signature);
+      this.parameterTypes = extractParamTypesOfCallableInString(signature);
```
Comment (lazaroclapp) [inline injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java:71]: Are `extractCallableName` and `extractParamTypesOfCallableInString` used outside this class? If not, let's make them private methods of `SignatureMatcher` and consider extracting this class as a top level class in its own file.

**Review by lazaroclapp — COMMENTED** [review]
Mostly looks ready to me, but wondering if we can extract `SignatureMatcher` and its related methods into a top-level class. See below.

File: injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java (hunk 11 above)
Comment (nimakarimipour) [reply injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java]: No they can be internal. Moved the Signature Matcher class to a top level class. Please find it here: c33e8b35e3db38385d303aacf237a2d5b7282677

**Review by lazaroclapp — APPROVED** [review]
LGTM! 🎉

**Comment by nimakarimipour** [comment]
@ketkarameya Please let me know once you approve this and I will land this.

**Review by ketkarameya — APPROVED** [review]
LGTM !
